### ISSUE TITLE
Cannot connect homey bridge with Somfy tahoma ap.

### ISSUE THREAD

**Issue by arjen1981x** [AdyRock/com.somfy.tahoma#108] opened 2023-06-06 05:56 UTC
Cannot connect to homey bridge .After login i get the message, too many login attemps. Allready deleted the app / my account but doenst help.

**Comment by arjen1981x** [comment] 2023-06-06 05:58
![Screenshot_20230606-075037~2](https://github.com/AdyRock/com.somfy.tahoma/assets/135688845/aeb9d15a-50b4-4fe4-8453-411ddea68bca)

**Comment by AdyRock** [comment] 2023-06-06 08:00
This is a known issue. Somfy have blocked the IP address of one of Homey servers.
Once all instances of the app running on that server back off for their long period, the block should be removed. Unfortunately, every time an instance tries to login it resets the block timer.

**Comment by arjen1981x** [comment] 2023-06-06 09:47
Tnx for your reply. Any indication of timing regarding the server?

Best

Arjen

Op di 6 jun. 2023 10:00 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2023-06-06 12:05
Unfortunately I have no idea. I was hoping it would be cleared by now. The problem is there are now nearly 3000 cloud users of the app and all have to be quiet for at least 12 hours.

**Comment by MJans72** [comment] 2023-06-07 16:38
I have the same issue since 31 May and trying several times to logon but everytime it fails

**Comment by arjen1981x** [comment] 2023-06-07 19:38
We need to stay quiet for 12 hours and not logging. Which is nearly impossible with 3000 users....

**Comment by tino708** [comment] 2023-06-08 20:52
Hi, is it even possible to solve the problem or can I abolish my homey again? A large part of my products are from somfy but should communicate with a few better functioning products.

**Comment by AdyRock** [comment] 2023-06-08 23:33
I have published a new test version and submitted it for release. This version has a different method of holding back login attempts that survives rebooting etc, so hopefully it will allow the attempts to pause for long enough to let the block be removed.

**Comment by MJans72** [comment] 2023-06-11 20:17
I tried this version but received the 401 error now. Is that still the same ?

**Comment by tino708** [comment] 2023-06-11 20:46
Hello, no, it should be a new mistake now. I am now only being written that there was an error when sending. The login error no longer appearsMit freundlichen Grüßen Tino Wiedemuth Am 11.06.2023 um 22:17 schrieb MJans72 ***@***.***>:﻿
I tried this version but received the 401 error now. Is that still the same ?

**Comment by AdyRock** [comment] 2023-06-12 02:56
Until everyone is on this version it won't fix the issue as those on the older version will still be causing the block time to reset. 
Note: not all cloud users are affected as Homey is hosted on more than one server and the block is on an IP address.

**Comment by arjen1981x** [comment] 2023-06-14 16:51
Is the problem with the block solved?

**Comment by MJans72** [comment] 2023-06-14 16:55
It is working again since this afternoon.
I hope it will stay like this.
Thanks!
Enjoy your day!

________________________________
Van: arjen1981x ***@***.***>
verzonden: woensdag 14 juni 2023 18:52
Aan: AdyRock/com.somfy.tahoma
Cc: Marcel Janson; Manual
Onderwerp: Re: [AdyRock/com.somfy.tahoma] Cannot connect homey bridge with Somfy tahoma ap. (Issue #108)


Is the problem with the block solved?

**Comment by tino708** [comment] 2023-06-14 16:55
Mega, it works again!!!!

 Thank you very much

Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 14.06.2023 um 18:51 schrieb arjen1981x ***@***.***>:
> 
> Is the problem with the block solved?

**Comment by arjen1981x** [comment] 2023-06-15 05:03
Doenst work for me :( installed the new app and receive the message "no new devices available"

**Comment by AdyRock** [comment] 2023-06-15 05:50
Directly after seeing that message, can you create an app diagnostics report so I can check what it finds.

**Comment by tino708** [comment] 2023-06-15 05:54
Unfortunately, I can't check that until tomorrow. I'm not at home today.

Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 15.06.2023 um 07:04 schrieb arjen1981x ***@***.***>:
> 
> Doenst work for me :( installed the new app and receive the message "no new devices available"

**Comment by AdyRock** [comment] 2023-06-15 07:04
On theory you can do that from anywhere with the Homey mobile app, but no problem either way.

**Comment by arjen1981x** [comment] 2023-06-15 14:36
![Screenshot_20230615-184741](https://github.com/AdyRock/com.somfy.tahoma/assets/135688845/fbb521cf-dcb2-40cf-b194-ee13c542c13c)
> Directly after seeing that message, can you create an app diagnostics report so I can check what it finds.

eeeb906d-551e-4d76-acce-8eafd83f7fc2   this is de code for the report. Tx for looking into this

**Comment by AdyRock** [comment] 2023-06-15 18:34
@arjen1981x I'm not finding the log. Did you create the log from the app page or Homey settings?
The one I need is from More (bottom right corner of the main screen) - Apps, then tap Somfy Tahoma and Connexoon, then tap on the cog in the top right corner and then Create Diagnostics Report.

**Comment by arjen1981x** [comment] 2023-06-15 20:06
> @arjen1981x I'm not finding the log. Did you create the log from the app page or Homey settings? The one I need is from More (bottom right corner of the main screen) - Apps, then tap Somfy Tahoma and Connexoon, then tap on the cog in the top right corner and then Create Diagnostics Report.

Ive used this screen 
![Screenshot_20230615-220519](https://github.com/AdyRock/com.somfy.tahoma/assets/135688845/afa4e5ee-a54e-4a56-9b45-8963659a42c1)

Also made a new report 0abb82ae-6eb9-45e0-a034-a7f88eb85285

**Comment by arjen1981x** [comment] 2023-06-16 14:25
Can you find the new log? I can try to make a log again?

**Comment by tino708** [comment] 2023-06-16 15:29
Hello, attached is the diagnostic code

EFAC0662




Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 15.06.2023 um 07:50 schrieb Adrian Rockall ***@***.***>:
> 
> Directly after seeing that message, can you create an app diagnostics report so I can check what it finds.

**Comment by tino708** [comment] 2023-06-16 15:35
0d0a0c97-c2a8-4470-a123-f9b70a72530f


Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 15.06.2023 um 22:06 schrieb arjen1981x ***@***.***>:
> 
> 0abb82ae-6eb9-45e0-a034-a7f88eb85285

**Comment by MJans72** [comment] 2023-06-17 08:48
I receive the 401 again. Before yesterday it worked for a short period. Yesterday nothing worked I had on all the items a red exclamation mark and later Hue was working again but the Somfy items stopped working again. I did see on the website that the cloud of the bridge did have an issue and after that I have this issue again.

**Comment by tino708** [comment] 2023-06-19 07:13
Hello, nothing works for me again, he has the mistake again



Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 17.06.2023 um 10:48 schrieb MJans72 ***@***.***>:
> 
> I receive the 401 again. Before yesterday it worked for a short period. Yesterday nothing worked I had on all the items a red exclamation mark and later Hue was working again but the Somfy items stopped working again. I did see on the website that the cloud of the bridge did have an issue and after that I have this issue again.

**Comment by arjen1981x** [comment] 2023-06-22 08:18
Any updates on this topic?

**Comment by tino708** [comment] 2023-06-22 15:47
Everything is working for me again at the momentMit freundlichen Grüßen Tino Wiedemuth Am 22.06.2023 um 10:18 schrieb arjen1981x ***@***.***>:﻿
Any updates on this topic?

**Comment by Ja4Novo** [comment] 2023-06-22 17:59
I still have an issue connecting to tahoma server. (vers 4.0.38).

**Comment by arjen1981x** [comment] 2023-06-22 20:35
> I still have an issue connecting to tahoma server. (vers 4.0.38).

Same here....

**Comment by arjen1981x** [comment] 2023-06-24 08:39
I works again for me!

**Comment by Ja4Novo** [comment] 2023-07-07 20:29
Again error?

**Comment by tino708** [comment] 2023-07-07 22:04
Yes, I can't do it either.

Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 07.07.2023 um 22:29 schrieb Ja4Novo ***@***.***>:
> 
> Again error?

**Comment by tino708** [comment] 2023-07-31 17:24
Hello, nothing works for me anymore. Do you have any idea if the problems can be solved in the long term? Many thanks in advance

Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 08.07.2023 um 00:04 schrieb Tino Wiedemuth ***@***.***>:
> 
> ﻿Yes, I can't do it either.
> 
> Mit freundlichen Grüßen 
> Tino Wiedemuth 
> 
>> Am 07.07.2023 um 22:29 schrieb Ja4Novo ***@***.***>:
>> 
>> Again error?

**Comment by AdyRock** [comment] 2023-07-31 17:40
Have you tried the test version?

**Comment by tino708** [comment] 2023-07-31 18:35
No, which trial version?Mit freundlichen Grüßen Tino Wiedemuth Am 31.07.2023 um 19:40 schrieb Adrian Rockall ***@***.***>:﻿
Have you tried the test version?

**Comment by AdyRock** [comment] 2023-07-31 18:42
Version 4.0.51.
Just add test to the end of the URL in the Athom store.

**Comment by tino708** [comment] 2023-07-31 19:19
Thank you, it works

Mit freundlichen Grüßen 
Tino Wiedemuth 

> Am 31.07.2023 um 20:42 schrieb Adrian Rockall ***@***.***>:
> 
> 4.0.51.

**Closed as completed** 2024-07-24 04:52 UTC
