### ISSUE TITLE
Cannot add devices to Tacoma mini

### ISSUE THREAD

**Issue by bijvejos** [AdyRock/com.somfy.tahoma#73] opened 2022-07-25 14:40 UTC
Hi Adrian. 

I have 3 Somfy rts devices: 1 outside (horizontal) terrace screen, 2 outside vertical screens. 
I installed / control them using a Tahoma mini bridge, and Tahoma app.

I entered Homey Beta, no physical bridge [yet].

I installed your app on homey cloud, but can't install Somfy [rts] devices.  

I tried many different combinations, but always end up with a Somfy login screen, that disappears before I have a chance to enter credentials, 
followed by a message that no devices can be added. 

Any idea how to solve this?

Thanks, Jos.

**Comment by AdyRock** [comment] 2022-07-25 15:57
Once the app has logged into your account once it will skip passed the login when adding devices, so have you managed to enter your credentials at least once?

If that is the case then trying different device types to add is the only option.

From the Homey phone app you can go to the Apps section, select the Somfy and Connexoon app then tap on the gear wheel in the top right corner and then tap on Create Diagnostics Report. That will send some information to me but often it is useless so it is a long shot.

**Comment by bijvejos** [comment] 2022-07-25 16:31
Thanks for the quick reply.
.I must have logged in succesfuly at some stage, yes.  So that would explain skipping the login (but I can see it in a flash).  

.I created a diagnostic report, Id in your mail.

**Comment by bijvejos** [comment] 2022-07-25 16:32
2a6a6db1-ef7e-4672-bbfa-589de6ea1bf4



Op ma 25 jul. 2022 17:57 schreef Adrian Rockall ***@***.***>:

**Comment by bijvejos** [comment] 2022-07-25 16:34
Adding other devicetypes yield same result.

**Comment by AdyRock** [comment] 2022-07-25 16:57
Can you install the test version https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/
Then try adding your devices and send the diagnostics log again.
I am sending the logged devices to the console to see if it will be captured by the report.

**Comment by bijvejos** [comment] 2022-07-25 18:16
Thanks Adrian. Same results. Here's the code..
fdf5da28-7b8d-4587-a107-834dc73397c9

Cheers
Jos


Op ma 25 jul. 2022 18:57 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-25 19:06
OK, that didn't work so I have tried another way. Can you do the same again please.

**Comment by bijvejos** [comment] 2022-07-25 20:44
Here goes..

9f95d49a-3575-40a2-9bcc-29565210bb16

Op ma 25 jul. 2022 21:06 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-25 21:42
Hmm, the log is showing v4.0.3 still. The new version is 4.0.4 so it seems the app hasn't updated. Could you go to the store and install it again. Then make sure you try to add a device  and then send the log.

```
A user has submitted a diagnostics report for com.somfy.tahoma (v4.0.3).

You can reply to this e-mail to get in touch with the user. Note that the user will be able to see your e-mail address.
Note: this log has been manually submitted by a user.
    Log ID: 9f95d49a-3575-40a2-9bcc-29565210bb16

    User Message:
    2nd attempt

    stdout:
    n/a

    stderr:
    n/a
```

**Comment by bijvejos** [comment] 2022-07-26 07:26
Reinstalled the app using
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/
But still get v4.0.3
Tried adding a device anyway, and now I was able to enter user id/password.
But no succes. Adding 2nd device skipped login, but no success.

Can't generate a report.






Op ma 25 jul. 2022 23:42 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-26 07:33
That's strange. Does it show as v4.0.4 in the store?
![image](https://user-images.githubusercontent.com/38184396/180949389-66ebc5c1-bae8-489a-943b-d720d8e288a8.png)

Maybe try to remove the app and install it again.

**Comment by bijvejos** [comment] 2022-07-26 08:34
Is there an option to reset the homey app? I would have no problems to do
so.



Op di 26 jul. 2022 09:33 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-26 08:45
The only way is to removed it and then install it again.

**Comment by bijvejos** [comment] 2022-07-26 09:57
Ok..  un/re installed homey beta cloud app,  setup house, installed tahoma
prod app: no change.
Uninstalled tahoma prod app, installed tahoma test app with your url. App
text says v403, but looking in app info, it says v404 [as changelog does].

Added 2 devices. 1st let me login to Somfy, 2nd skipped login. Same error:
no new devices found.
It now allows me te send problem report:
be3528a0-c9b9-440a-9187-62e90d3fb092

[ 'Send report' button will stay dimmed if text starts with a number.. ]

Cheers, Jos.

Op di 26 jul. 2022 10:45 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-26 10:30
I have asked Athom if there is a know issue with updating an app on Homey as this is very strange.

**Comment by AdyRock** [comment] 2022-07-27 19:25
Could you try the update again. I have just updated mine successfully so hopefully Athom has fixed that issue now.

**Comment by bijvejos** [comment] 2022-07-27 20:03
Great! Will do so next Saturday. I'll let you know by then.

Op wo 27 jul. 2022 21:25 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-27 20:16
Ok, no rush.

**Comment by bijvejos** [comment] 2022-07-29 16:54
Ok.. I installed v4.0.6 experimental, and tried to add some different
devices.
I get Somfy login each time, but after hitting login, I get message
'Request failed with status code 401'

I can't send a report, so I guess there is none.

Hope you can find a way forward..

Cheers Jos.

Op wo 27 jul. 2022 22:16 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-29 18:39
It seems a lot of Somfy users are having problems logging in at the moment so I think they have a problem with their servers.

**Comment by bijvejos** [comment] 2022-07-30 13:15
Still failing with 401.
Installed 3.0.35  and made a report:
8a53abf0-07b5-41a8-a768-4bfd483ddd6e

Jos.

Op vr 29 jul. 2022 20:40 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-07-30 13:20
Still empty:
```
A user has submitted a diagnostics report for com.somfy.tahoma (v3.0.35).

You can reply to this e-mail to get in touch with the user. Note that the user will be able to see your e-mail address.
Note: this log has been manually submitted by a user.
    Log ID: 8a53abf0-07b5-41a8-a768-4bfd483ddd6e

    User Message:
    Attempt Four

    stdout:
    n/a

    stderr:
    n/a
```

I have a support request with Athom as there is obviously something wrong with the error reporting on Homey.

**Comment by bijvejos** [comment] 2022-07-30 15:27
Thanks Adrian. Waiting for Athome to contact.
Mean time, I tried the same using app v4.0.6 no surprise: same issue.
Report Id is fcfdf088-e20b-49f9-85f1-b8d51162d6fb

Cheers, Jos.

Op za 30 jul. 2022 15:21 schreef Adrian Rockall ***@***.***>:

**Comment by bijvejos** [comment] 2022-08-03 12:51
Saw Jos Groenewegen's issue. 
I'm contacting somfy for assistance.

**Comment by bijvejos** [comment] 2022-08-04 12:00
Somfy reset tahoma device, I removed and setup Somfy, Athom apps. No change.

Logged issue with Somfy cloud.

**Comment by Mironman** [comment] 2022-08-10 14:46
Hi, I have the same problem with conectivity kit (401 error).
I asked Somfy and they says that somfy-connect is not accesible with connectivity kit. 
There is a way, because with IFTTT it works.
Br,

**Comment by bijvejos** [comment] 2022-08-10 17:34
Same here. IFTTT connects, and Google home as well.

Cheers
Jos

Op wo 10 aug. 2022 16:46 schreef Mironman ***@***.***>:

**Comment by AdyRock** [comment] 2022-08-10 18:48
I have passed the information on to my contact at Somfy but I got an automatic reply saying he is on holiday until the end of August.

**Comment by AdyRock** [comment] 2022-08-10 18:52
Is everyone here using Homey (cloud) or are some using Homey Pro?

Also I believe there is a mixture of Somfy hubs, so could you confirm which one you are using?

**Comment by bijvejos** [comment] 2022-08-10 19:36
Homey Cloud and European Hub

Op wo 10 aug. 2022 20:52 schreef Adrian Rockall ***@***.***>:

**Comment by Mironman** [comment] 2022-08-11 09:54
Homey bridge (+cloud) and Somfy connection kit. 
I think connection kit is maybe a tahoma with different coverage because on somfy account it's caled Tahoma and it use TaHoMa app.

**Comment by AdyRock** [comment] 2022-08-11 10:11
So, it could be a Homey cloud issue. In the past Somfy blocked some cloud IP address as it saw a lot of connections from the same one and marked it as an attack. I thought that had been fixed but maybe they just removed the IP's from the blacklist and they have got back in again. 
Athom can't provide me with a list of IP addresses that will be used as Homey is hosted on third party servers.

**Comment by bijvejos** [comment] 2022-08-11 14:45
[image: IMG_20220804_101330.jpg]
Here's mine...

Grt, Jos.
-------------------------------------------------------------------------------------------------------------------------


Op do 11 aug. 2022 om 11:54 schreef Mironman ***@***.***>:

**Comment by AdyRock** [comment] 2022-08-30 22:17
There is a new test version that changes the way the information is logged to see if Homey can report it with the Create Diagnostic report function.

**Comment by bijvejos** [comment] 2022-08-31 07:27
Thanks for that Adrian. I tried adding a device once more, got 401 error,
and generated a problem report.
I'd is 2990598c-581d-41f8-9c14-4f281bc19269

Hope you get some result now.

Cheers,
Jos.

Op wo 31 aug. 2022 00:17 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2022-08-31 09:25
Well it is better as I now have some information in the log:
```
Note: this log has been manually submitted by a user.
    Log ID: 2990598c-581d-41f8-9c14-4f281bc19269

    User Message:
    Report for 401 error

    stdout:
    n/a

    stderr:
    Stop sync requested, 
stopSync, Stopping Event Polling
Tahoma Login, {
  "message": "Start OAuth Login",
  "stack": {
    "linkURL": "default"
  }
}
Tahoma Login, {
  "message": "Start Simple Login",
  "stack": {
    "attempts": 1
  }
}
Tahoma Login, Error: Cannot read properties of null (reading 'name')
Tahoma Login, Error: Cannot read properties of null (reading 'name')
Login, Error: Cannot read properties of null (reading 'name')
Tahoma Login, {
  "message": "Start Simple Login",
  "stack": {
    "attempts": 1,
    "linkURL": "default"
  }
}
Tahoma Login, Error: Request failed with status code 401
Stop sync requested, 
stopSync, Stopping Event Polling
Tahoma Login, {
  "message": "Start OAuth Login",
  "stack": {
    "linkURL": "default"
  }
}
Tahoma Login, {
  "message": "Start Simple Login",
  "stack": {
    "attempts": 2
  }
}
Tahoma Login, Error: Cannot read properties of null (reading 'name')
Tahoma Login, Error: Cannot read properties of null (reading 'name')
Login, Error: Cannot read properties of null (reading 'name')
Tahoma Login, {
  "message": "Start Simple Login",
  "stack": {
    "attempts": 2,
    "linkURL": "default"
  }
}
Tahoma Login, Error: Request failed with status code 401
```
But I can't see anywhere in my code that I am try to read a property called 'name'. So, still a mystery, but at least it is something to work on. Of course it could be a side affect of the new logging method and not the cause of the error.
The good thing is I can see it is trying both login methods, which rules out one question I had in mind.

**Comment by bijvejos** [comment] 2022-10-11 07:41
Nope, shows 4.0.3
I did remove/install..



Op di 26 jul. 2022 09:33 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2024-07-24 04:33
I'm looking through old issues and noticed this doesn't seem to be resolved. Is this working now?

**Comment by bijvejos** [comment] 2024-07-24 06:51
Thanks Adrian.
I switch to HA, so no sure if this works now.
Cheers,
Jos.

Op wo 24 jul. 2024 06:33 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment] 2024-07-24 07:39
Ok, thank you for the update.

**Closed as completed** 2024-07-24 07:39 UTC
